name: API Dashboard CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      #  Checkout mã nguồn từ nhánh "production" của repository.
      - name: Checkout github
        uses: actions/checkout@v2
        
     # Đăng nhập vào Docker Hub bằng tên người dùng và mật khẩu được lưu trữ trong secrets.
      - name: Login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # Chuẩn bị Docker Buildx để thực hiện việc xây dựng hình ảnh Docker platform.
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      # Caching các lớp hình ảnh Docker để tăng tốc độ xây dựng trong các lần chạy tiếp theo.
      - name: Cache Docker Image Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Xây dựng và đẩy hình ảnh Docker cho thành phần client của ứng dụng API Dashboard.
      - name: Build and Push Docker image for client
        uses: docker/build-push-action@v2
        id: docker_build_client
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-dashboard
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Xác minh hình ảnh Docker đã được xây dựng và đẩy thành công bằng cách in ra giá trị băm (digest) của hình ảnh.
      - name: Verify
        run: echo ${{ steps.docker_build_client.outputs.digest }}
